In [116]:
import pandas as pd
import numpy as np
import os
import datetime
import win32com.client
import time
import getpass
from datetime import timedelta

usuario = getpass.getuser()

inicio = time.time()
# %%
import os
from datetime import datetime

In [117]:
import os
import pandas as pd
from datetime import datetime, timedelta

# Define the directory path
carpeta_fechas = "C:/Users/lravlic/Inchcape/Planificación y Compras Chile - Documentos/Planificación y Compras KPI-Reportes/Actualización diaria fechas DT/Actualización Diaria fechas Dts R3"

# Maximum number of days to look back
max_days_back = 30

# Function to try reading the file for a given date
def try_read_file(date_str):
    ruta_arch = f'{date_str} Actualizacion fechas diaria  Dts OEM.xlsx'
    ruta = os.path.join(carpeta_fechas, ruta_arch)
    if os.path.exists(ruta):
        df_fechas = pd.read_excel(ruta, sheet_name='Data')
        print(f"File found: {ruta}")
        return df_fechas
    return None

# Try to find a file for today and up to max_days_back days ago
for days_back in range(max_days_back + 1):
    date_to_try = (datetime.today() - timedelta(days=days_back)).strftime('%d-%m-%Y')
    df_fechas = try_read_file(date_to_try)
    if df_fechas is not None:
        break
else:
    print("No file found within the given date range.")

# Continue with your further processing
if df_fechas is not None:
    # Do something with df_fechas
    pass
else:
    # Handle the case where no file was found
    pass

File found: C:/Users/lravlic/Inchcape/Planificación y Compras Chile - Documentos/Planificación y Compras KPI-Reportes/Actualización diaria fechas DT/Actualización Diaria fechas Dts R3\11-07-2024 Actualizacion fechas diaria  Dts OEM.xlsx

In [118]:
df_fechas['Nro. DT'].to_clipboard(index = False, header = False)

In [119]:
df_fechas['Nro. DT'].nunique()

1242

In [120]:
try:
    # Initialize SAP GUI scripting
    SapGuiAuto = win32com.client.GetObject("SAPGUI")
    application = SapGuiAuto.GetScriptingEngine
    if not application:
        raise Exception("Error obtaining SAP GUI application")

    connection = application.Children(0)
    if not connection:
        raise Exception("Error obtaining SAP GUI connection")

    session = connection.Children(0)
    if not session:
        raise Exception("Error obtaining SAP GUI session")

    # Connect to WScript if available
    try:
        WScript = win32com.client.Dispatch("WScript")
        WScript.ConnectObject(session, "on")
        WScript.ConnectObject(application, "on")
    except Exception as e:
        print(f"Error connecting to WScript: {str(e)}")

    # Maximize the window
    session.findById("wnd[0]").maximize()

    # Execute transaction
    session.findById("wnd[0]/tbar[0]/okcd").text = "zmm_seguim_comex_cl"
    session.findById("wnd[0]").sendVKey(0)

    # Press buttons
    session.findById("wnd[0]/usr/btn%_P_TKNUM_%_APP_%-VALU_PUSH").press()
    session.findById("wnd[1]/tbar[0]/btn[24]").press()
    session.findById("wnd[1]/tbar[0]/btn[0]").press()
    session.findById("wnd[1]/tbar[0]/btn[8]").press()
    session.findById("wnd[0]").sendVKey(8)

    # Export to Excel
    session.findById("wnd[0]/usr/cntlALV_COMEX/shellcont/shell").pressToolbarContextButton("&MB_EXPORT")
    session.findById("wnd[0]/usr/cntlALV_COMEX/shellcont/shell").selectContextMenuItem("&XXL")
    session.findById("wnd[1]/tbar[0]/btn[0]").press()

    # Set file path and name
    session.findById("wnd[1]/usr/ctxtDY_PATH").text = "C:\\Users\\lravlic\\Codigos\\automatizacion_gere_comex"
    session.findById("wnd[1]/usr/ctxtDY_FILENAME").text = "comex.XLSX"
    session.findById("wnd[1]/usr/ctxtDY_FILENAME").caretPosition = 5
    session.findById("wnd[1]/tbar[0]/btn[11]").press()

    # Close SAP windows
    session.findById("wnd[0]").sendVKey(3)
    session.findById("wnd[0]").sendVKey(3)

except Exception as e:
    print(f"Error during SAP GUI interaction: {str(e)}")

Error connecting to WScript: (-2147221005, 'Cadena clase no válida', None, None)

In [121]:
# %%
import xlwings as xw
try:
    book = xw.Book("C:/Users/lravlic/Codigos/automatizacion_gere_comex/comex.XLSX")
    book.close()
except Exception as e:
    print(e)

In [122]:
comex = pd.read_excel("C:/Users/lravlic/Codigos/automatizacion_gere_comex/comex.XLSX")

In [123]:
dts_a_mir6 = comex[comex['Estatus']=='CERRADO']

In [124]:
dts_a_mir6.Estatus.value_counts()

Estatus
CERRADO    1124
Name: count, dtype: int64

In [125]:
dts_a_mir6['Nro. DT asociado'] = dts_a_mir6['Nro. DT asociado'].astype(str)

# Create the new column 'DT' by concatenating '*' before and after the values
dts_a_mir6['DT'] = '*' + dts_a_mir6['Nro. DT asociado'] + '*'

C:\Users\lravlic\AppData\Local\Temp\ipykernel_2300\1582769832.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dts_a_mir6['Nro. DT asociado'] = dts_a_mir6['Nro. DT asociado'].astype(str)
C:\Users\lravlic\AppData\Local\Temp\ipykernel_2300\1582769832.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dts_a_mir6['DT'] = '*' + dts_a_mir6['Nro. DT asociado'] + '*'

In [126]:
dts_a_mir6['DT'].to_clipboard(index=False,header=False)

In [127]:
import win32com.client

# Initialize SAP GUI scripting
SapGuiAuto = win32com.client.GetObject("SAPGUI")
application = SapGuiAuto.GetScriptingEngine
connection = application.Children(0)
session = connection.Children(0)

# Maximize the window
session.findById("wnd[0]").maximize()

# Enter transaction code "mir6"
session.findById("wnd[0]/tbar[0]/okcd").text = "mir6"
session.findById("wnd[0]").sendVKey(0)

# Clear and set the focus on the user field
session.findById("wnd[0]/usr/txtSO_USNAM-LOW").text = ""
session.findById("wnd[0]/usr/txtSO_USNAM-LOW").setFocus()
session.findById("wnd[0]/usr/txtSO_USNAM-LOW").caretPosition = 0
session.findById("wnd[0]").sendVKey(0)

# Set focus on the text field and perform actions
session.findById("wnd[0]/usr/txtSO_BKTXT-LOW").setFocus()
session.findById("wnd[0]/usr/txtSO_BKTXT-LOW").caretPosition = 0
session.findById("wnd[0]/usr/btn%_SO_BKTXT_%_APP_%-VALU_PUSH").press()
session.findById("wnd[1]/tbar[0]/btn[24]").press()
session.findById("wnd[1]/tbar[0]/btn[0]").press()
session.findById("wnd[1]/tbar[0]/btn[8]").press()

# Toggle checkboxes
session.findById("wnd[0]/usr/chkP_IV_BG").setFocus()
session.findById("wnd[0]/usr/chkP_IV_BG").selected = False
session.findById("wnd[0]").sendVKey(2)
session.findById("wnd[0]/usr/chkP_IV_BG").selected = True
session.findById("wnd[0]/usr/chkP_IV_IS").setFocus()
session.findById("wnd[0]/usr/chkP_IV_IS").selected = True
session.findById("wnd[0]/usr/chkP_IV_OV").setFocus()
session.findById("wnd[0]/usr/chkP_IV_OV").selected = True
session.findById("wnd[0]/usr/chkP_IV_STO").setFocus()
session.findById("wnd[0]/usr/chkP_IV_STO").selected = True
session.findById("wnd[0]/usr/chkP_IV_EDI").setFocus()
session.findById("wnd[0]/usr/chkP_IV_EDI").selected = True
session.findById("wnd[0]/usr/chkP_IV_RAP").setFocus()
session.findById("wnd[0]/usr/chkP_IV_RAP").selected = True
session.findById("wnd[0]/usr/chkP_IV_BAP").setFocus()
session.findById("wnd[0]/usr/chkP_IV_BAP").selected = True
session.findById("wnd[0]/usr/chkP_IV_PAR").setFocus()
session.findById("wnd[0]/usr/chkP_IV_PAR").selected = True
session.findById("wnd[0]/usr/chkP_IV_ERS").setFocus()
session.findById("wnd[0]/usr/chkP_IV_ERS").selected = True
session.findById("wnd[0]/usr/chkP_IV_SRM").setFocus()
session.findById("wnd[0]/usr/chkP_IV_SRM").selected = True
session.findById("wnd[0]/usr/chkP_IV_TP").setFocus()
session.findById("wnd[0]/usr/chkP_IV_TP").selected = True
session.findById("wnd[0]/usr/chkP_IV_A2A").setFocus()
session.findById("wnd[0]/usr/chkP_IV_A2A").selected = True
session.findById("wnd[0]/usr/chkP_IV_B2B").setFocus()
session.findById("wnd[0]/usr/chkP_IV_B2B").selected = True

# Execute commands and navigate
session.findById("wnd[0]").sendVKey(8)
session.findById("wnd[0]/tbar[0]/btn[86]").press()
session.findById("wnd[0]/tbar[1]/btn[33]").press()
session.findById("wnd[1]/usr/lbl[1,6]").setFocus()
session.findById("wnd[1]/usr/lbl[1,6]").caretPosition = 7
session.findById("wnd[1]").sendVKey(2)
session.findById("wnd[0]/tbar[1]/btn[43]").press()
session.findById("wnd[1]/tbar[0]/btn[0]").press()

# Set the file path for export
session.findById("wnd[1]/usr/ctxtDY_PATH").text = "C:\\Users\\lravlic\\Codigos\\land_cost"
session.findById("wnd[1]/usr/ctxtDY_PATH").setFocus()
session.findById("wnd[1]/usr/ctxtDY_PATH").caretPosition = 34
session.findById("wnd[1]/tbar[0]/btn[11]").press()

# Close the windows
session.findById("wnd[0]").sendVKey(3)
session.findById("wnd[0]").sendVKey(3)
session.findById("wnd[0]").sendVKey(3)

In [128]:

try:
    book = xw.Book("C:/Users/lravlic/Codigos/land_cost/export.XLSX")
    book.close()
except Exception as e:
    print(e)

In [129]:
df_mir6 = pd.read_excel("C:/Users/lravlic/Codigos/land_cost/export.XLSX")

In [130]:
df_mir6_filtro_yr = df_mir6[df_mir6['Fe.contabilización'].dt.year >=2024]

In [131]:
df_mir6_filtro_yr['Texto cab.documento'] = pd.to_numeric(df_mir6_filtro_yr['Texto cab.documento'], errors='coerce')

# Convert the column to integers, dropping NaN values first
df_mir6_filtro_yr = df_mir6_filtro_yr.dropna(subset=['Texto cab.documento'])
df_mir6_filtro_yr['Texto cab.documento'] = df_mir6_filtro_yr['Texto cab.documento'].astype(int)

# Display the DataFrame to verify the changes
print(df_mir6_filtro_yr['Texto cab.documento'])

159      19551
160      19555
161      19660
162      19760
163      19663
         ...
25498    33605
25499    33605
25500    33605
25501    33605
25502    33605
Name: Texto cab.documento, Length: 5425, dtype: int32

C:\Users\lravlic\AppData\Local\Temp\ipykernel_2300\2222300859.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mir6_filtro_yr['Texto cab.documento'] = pd.to_numeric(df_mir6_filtro_yr['Texto cab.documento'], errors='coerce')

In [132]:
df_mir6_filtro_yr['Texto cab.documento'] = df_mir6_filtro_yr['Texto cab.documento'].astype('str')

In [133]:
filtered_df = df_mir6_filtro_yr[df_mir6_filtro_yr['Texto cab.documento'].str.len() <= 6]

# Print the filtered DataFrame
print(filtered_df['Texto cab.documento'])

159      19551
160      19555
161      19660
162      19760
163      19663
         ...
25498    33605
25499    33605
25500    33605
25501    33605
25502    33605
Name: Texto cab.documento, Length: 5386, dtype: object

In [134]:
filtered_df.columns

Index(['Tipo de cambio', 'Texto cab.documento', 'Referencia',
       'Nombre del usuario', 'Nombre 1', 'Nº documento factura', 'Moneda',
       'Impte.bruto factura', 'Fecha de entrada', 'Fecha de documento',
       'Fe.descto.', 'Fe.contabilización', 'Emisor de factura', 'Ejercicio',
       'Creado por', 'Código transacción', 'Clase de documento',
       'Base retención', 'Asignación', 'Anulado con'],
      dtype='object')

In [135]:
filtered_df['Referencia'].to_clipboard(header=False, index=False)
# Initialize SAP GUI scripting
SapGuiAuto = win32com.client.GetObject("SAPGUI")
application = SapGuiAuto.GetScriptingEngine
connection = application.Children(0)
session = connection.Children(0)

# Maximize the window
session.findById("wnd[0]").maximize()

# Execute transaction code "fbl3n"
session.findById("wnd[0]/tbar[0]/okcd").text = "fbl3n"
session.findById("wnd[0]").sendVKey(0)

# Interact with elements
session.findById("wnd[0]/tbar[1]/btn[16]").press()
session.findById("wnd[0]/usr/ssub%_SUBSCREEN_%_SUB%_CONTAINER:SAPLSSEL:2001/ssubSUBSCREEN_CONTAINER2:SAPLSSEL:2000/cntlSUB_CONTAINER/shellcont/shellcont/shell/shellcont[1]/shell").selectNode("         37")
session.findById("wnd[0]/usr/ssub%_SUBSCREEN_%_SUB%_CONTAINER:SAPLSSEL:2001/ssubSUBSCREEN_CONTAINER2:SAPLSSEL:2000/cntlSUB_CONTAINER/shellcont/shellcont/shell/shellcont[1]/shell").topNode = "         30"
session.findById("wnd[0]/usr/ssub%_SUBSCREEN_%_SUB%_CONTAINER:SAPLSSEL:2001/ssubSUBSCREEN_CONTAINER2:SAPLSSEL:2000/cntlSUB_CONTAINER/shellcont/shellcont/shell/shellcont[1]/shell").doubleClickNode("         37")
session.findById("wnd[0]/usr/ssub%_SUBSCREEN_%_SUB%_CONTAINER:SAPLSSEL:2001/ssubSUBSCREEN_CONTAINER2:SAPLSSEL:2000/ssubSUBSCREEN_CONTAINER:SAPLSSEL:1106/btn%_%%DYN009_%_APP_%-VALU_PUSH").press()
session.findById("wnd[1]/tbar[0]/btn[24]").press()
session.findById("wnd[1]/tbar[0]/btn[0]").press()
session.findById("wnd[1]/tbar[0]/btn[8]").press()

# Set selection criteria
session.findById("wnd[0]/usr/radX_AISEL").select()
session.findById("wnd[0]/usr/ctxtSD_SAKNR-LOW").text = "1104040001"
session.findById("wnd[0]/usr/ctxtSD_BUKRS-LOW").text = "CL07"
session.findById("wnd[0]/usr/ctxtSO_BUDAT-LOW").text = "01.01.2024"
session.findById("wnd[0]/usr/ctxtSO_BUDAT-HIGH").text = "31.12.2024"
session.findById("wnd[0]/usr/ctxtSD_BUKRS-LOW").setFocus()
session.findById("wnd[0]/usr/ctxtSD_BUKRS-LOW").caretPosition = 4
session.findById("wnd[0]").sendVKey(8)

# Change selection criteria

session.findById("wnd[0]/usr/ctxtSD_BUKRS-LOW").text = "CL02"
session.findById("wnd[0]/usr/ctxtSD_BUKRS-LOW").setFocus()
session.findById("wnd[0]/usr/ctxtSD_BUKRS-LOW").caretPosition = 4
session.findById("wnd[0]").sendVKey(8)

# Execute commands and navigate
session.findById("wnd[0]/usr/lbl[29,2]").setFocus()
session.findById("wnd[0]/usr/lbl[29,2]").caretPosition = 69
session.findById("wnd[0]").sendVKey(16)
session.findById("wnd[1]/tbar[0]/btn[0]").press()

# Set the file path for export
session.findById("wnd[1]/usr/ctxtDY_PATH").setFocus()
session.findById("wnd[1]/usr/ctxtDY_PATH").caretPosition = 0
session.findById("wnd[1]").sendVKey(4)
session.findById("wnd[2]/usr/ctxtDY_PATH").text = "C:\\Users\\lravlic\\Codigos\\land_cost"
session.findById("wnd[2]/usr/ctxtDY_FILENAME").text = "iva_r3.XLSX"
session.findById("wnd[2]/usr/ctxtDY_FILENAME").caretPosition = 6
session.findById("wnd[2]/tbar[0]/btn[11]").press()
session.findById("wnd[1]/tbar[0]/btn[11]").press()

# Close the windows
session.findById("wnd[0]").sendVKey(3)
session.findById("wnd[0]").sendVKey(3)

try:
    book = xw.Book("C:/Users/lravlic/Codigos/land_cost/iva_r3.XLSX")
    book.close()
except Exception as e:
    print(e)
df_iva = pd.read_excel('iva_r3.xlsx')
df_iva=df_iva[['Referencia','Importe en moneda local']]
df_iva = df_iva.groupby('Referencia').max().reset_index()

filtered_df = filtered_df.merge(df_iva, left_on='Referencia',right_on='Referencia', how='left')
filtered_df['Importe en moneda local'].fillna(0, inplace=True)
filtered_df['Impte.bruto factura'] = filtered_df['Impte.bruto factura'] - filtered_df['Importe en moneda local']
filtered_df.drop(columns='Importe en moneda local', inplace=True)

In [136]:
filtered_df.head()

,Tipo de cambio,Texto cab.documento,Referencia,Nombre del usuario,Nombre 1,Nº documento factura,Moneda,Impte.bruto factura,Fecha de entrada,Fecha de documento,Fe.descto.,Fe.contabilización,Emisor de factura,Ejercicio,Creado por,Código transacción,Clase de documento,Base retención,Asignación,Anulado con
0,"1,00000",19551,0236960581,SROJASF,NaN,5112952310,CLP,0.0,2024-01-11,2024-01-09,2024-01-09,2024-01-11,10000788,2024,NaN,MIRO,KI,0,0236960581,NaN
1,"1,00000",19555,0236960587,SROJASF,NaN,5112952457,CLP,0.0,2024-01-11,2024-01-09,2024-01-09,2024-01-11,10000788,2024,NaN,MIRO,KI,0,0236960587,NaN
2,"1,00000",19660,0236966448,SROJASF,NaN,5112956420,CLP,0.0,2024-01-16,2024-01-13,2024-01-13,2024-01-16,10000788,2024,NaN,MIRO,KI,0,0236966448,NaN
3,"1,00000",19760,0236965402,SROJASF,NaN,5112956464,CLP,25314.0,2024-01-16,2024-01-12,2024-01-12,2024-01-16,10000788,2024,NaN,MIRO,KI,0,0236965402,NaN
4,"1,00000",19663,0236969029,SROJASF,NaN,5112956505,CLP,63816.0,2024-01-16,2024-01-15,2024-01-15,2024-01-16,10000788,2024,NaN,MIRO,KI,0,0236969029,NaN

In [137]:
filtered_df.to_parquet('base_landcost.parquet')

In [138]:
glosario = pd.read_csv('glosario.csv', sep=';', usecols=['CLASE', 'Denominación'])

In [139]:
tipo_gasto = pd.read_csv('tipo_de_gasto.csv', sep=';')

In [140]:
tipo_gasto.dropna(subset='R3', inplace=True)

In [141]:
tipo_gasto.drop_duplicates(subset='R3', inplace=True, keep='first')

In [142]:
filtered_df = filtered_df.merge(tipo_gasto, left_on='Emisor de factura', right_on='R3', how='left')

In [143]:
filtered_df[filtered_df['Tipo de gasto'].isna()]

Empty DataFrame
Columns: [Tipo de cambio, Texto cab.documento, Referencia, Nombre del usuario, Nombre 1, Nº documento factura, Moneda, Impte.bruto factura, Fecha de entrada, Fecha de documento, Fe.descto., Fe.contabilización, Emisor de factura, Ejercicio, Creado por, Código transacción, Clase de documento, Base retención, Asignación, Anulado con, Mar, Tipo de gasto, R3]
Index: []

[0 rows x 23 columns]

In [144]:
filtered_df.drop(columns=['Mar', 'R3'], inplace=True)

In [145]:
filtered_df.dtypes

Tipo de cambio                  object
Texto cab.documento             object
Referencia                      object
Nombre del usuario              object
Nombre 1                       float64
Nº documento factura             int64
Moneda                          object
Impte.bruto factura            float64
Fecha de entrada        datetime64[ns]
Fecha de documento      datetime64[ns]
Fe.descto.              datetime64[ns]
Fe.contabilización      datetime64[ns]
Emisor de factura               object
Ejercicio                        int64
Creado por                     float64
Código transacción              object
Clase de documento              object
Base retención                   int64
Asignación                      object
Anulado con                    float64
Tipo de gasto                   object
dtype: object

In [146]:
df_prov = pd.read_excel("C:/Users/lravlic/Inchcape/Planificación y Compras Chile - Documentos/Planificación y Compras Maestros/Maestro Proveedores/Base Proveedor OFICIAL OEM AXS.xlsx")

In [147]:
df_prov = df_prov[['Nombre de Proveedor','Equipo','Sector','Analista','Proveedor R3']]

In [148]:
df_fechas.columns

Index(['Creado el', 'Nro. DT', 'Marca/Producto', 'Proveedor',
       'Nombre Proveedor', 'País Origen', 'Moneda', 'Ref. Prefijo Emb.', 'Vía',
       'Vía (Texto)', 'Referencia', 'Documento de embarque', 'Cant. Factura',
       'Valor Fact.', 'Embarcador', 'Nombre del Embarcador',
       'Nave / Aerolínea', 'Voyage / Vuelo', 'Peso Bruto total', 'Volumen',
       'Pto. Origen', 'Pto. Destino', 'Nro. Cert. Origen', 'Nro. Cert. Seguro',
       'Estatus COMEX', 'Fe. INV', 'TF de INV', 'Fe. ATD', 'TF de ATD',
       'Fe. ATA', 'TF de ATA', 'Fe. Pago Aduana', 'TF Pago Aduana',
       'Fe. Alm. Logístico', 'TF Alm. Logístico', 'Fe. Fin Recep.Emb',
       'TF de Fin Recep. Emb', 'Fe. Centro Distribución',
       'TF. Centro Distribución', 'Fe. MIGO', 'TF de MIGO', 'Fe. Disp.últ.SKU',
       'TF.Disp.últ.SKU', 'OC-INV (R)', 'INV-ATD (R)', 'ATD-ATA (R)',
       'ATA-COMEX (R)', 'COMEX-ALM LOG (R)', 'LT Total (R)',
       'Fe. Entrega a Comex', 'ALM LOG - CD  (R)', 'CD - MIGO (R)',
       'MIGO - FIN RECEP (R)', 'FIN RECEP - DISPO (R)', 'Tipos de Fecha',
       'Mes ATA', 'Analista', 'Marca', 'Vencido INV', 'Vencido ETD',
       'Vencido ETA', 'Vencido COMEX', 'Vencido Centro Logístico',
       'Vencido Recep.', 'Vencido Dispo', 'Desviación ETD', 'Desviacion ETA ',
       'Desviacion CMX', 'Desviacion Clog ', 'Desviacion recep',
       'Desviación disp', 'Status 1', 'Status 2', 'Observación', 'Alerta'],
      dtype='object')

In [149]:
df_fechas.drop_duplicates(subset='Nro. DT', keep='first', inplace=True)

In [150]:
df_fechas['Nro. DT'] = df_fechas['Nro. DT'].astype('str')

In [151]:
df_prov.drop_duplicates(subset='Proveedor R3', keep='first', inplace=True)

In [152]:
filtered_df = filtered_df.merge(df_prov, left_on='Emisor de factura', right_on='Proveedor R3', how='left')
filtered_df = filtered_df.merge(df_fechas, left_on='Texto cab.documento', right_on='Nro. DT', how='left')

In [153]:
filtered_df = filtered_df.merge(df_fechas, left_on='Texto cab.documento', right_on='Nro. DT', how='left')

In [154]:
df_fechas

,Creado el,Nro. DT,Marca/Producto,Proveedor,Nombre Proveedor,País Origen,Moneda,Ref. Prefijo Emb.,Vía,Vía (Texto),...,Desviación ETD,Desviacion ETA,Desviacion CMX,Desviacion Clog,Desviacion recep,Desviación disp,Status 1,Status 2,Observación,Alerta
0,2024-01-10,19437,NaN,40001373,ANHUI JIANGHUAI AUTOMOBILE GROUP,CHINA,USD,JACA191-23-003,Z2,Aereo,...,0,0,0,0,0,0,0,NO,OK,False
1,2024-01-11,19531,NaN,40000199,CHANGAN INTERNATIONAL CORPORATION,CHINA,CNY,KVEC0124RA3-005,Z3,Maritimo,...,0,0,0,0,0,0,0,NO,OK,False
2,2024-01-11,19551,NaN,40000176,GREAT WALL MOTOR COMPANY LIMITED,CHINA,USD,GWCCL319-23-001,Z1,Courier,...,0,0,0,0,0,0,0,NO,OK,False
3,2024-01-11,19554,NaN,40000199,CHANGAN INTERNATIONAL CORPORATION,CHINA,CNY,CHC181-23-004,Z1,Courier,...,0,0,0,0,0,0,0,NO,OK,False
4,2024-01-11,19555,NaN,40000176,GREAT WALL MOTOR COMPANY LIMITED,CHINA,USD,GWCCL283-23-001,Z1,Courier,...,0,0,0,0,0,0,0,NO,OK,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1660,2024-07-10,34040,NaN,40000234,MARUTI SUZUKI INDIA LTD.,INDIA,USD,CHLSIM039-24-004,Z3,Maritimo,...,0,0,0,0,0,0,0,NO,OK,False
1662,2024-07-10,34124,NaN,40003526,PT SUZUKI INDOMOBIL SALES,INDONESIA,USD,CHLSNC019-24-001,Z1,Courier,...,0,0,0,0,0,0,0,NO,OK,False
1663,2024-07-10,34235,NaN,40002536,"HEFEI WINNING AUTO PARTS CO., LTD.",CHINA,USD,CHLHWC037-24-013,Z1,Courier,...,0,0,0,0,0,0,0,NO,OK,False
1664,2024-07-10,34237,NaN,40002536,"HEFEI WINNING AUTO PARTS CO., LTD.",CHINA,USD,CHLHWC038-24-002,Z1,Courier,...,0,0,0,0,0,0,0,NO,OK,False
1665,2024-07-10,34242,NaN,40003191,SUZUKI MOTOR CORPORATION,JAPON,JPY,CHLSJC050-24-001,Z1,Courier,...,0,0,0,0,0,0,0,NO,OK,False

In [155]:
columnas = ['Nro. DT','Proveedor','Nombre del Embarcador','Vía (Texto)', 'País Origen','Pto. Origen', 'Fe. ATA']
df_fechas_columnas = df_fechas[columnas]

In [156]:
df_fechas_columnas['Nro. DT'] = df_fechas_columnas['Nro. DT'].astype('str')

C:\Users\lravlic\AppData\Local\Temp\ipykernel_2300\4089450802.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fechas_columnas['Nro. DT'] = df_fechas_columnas['Nro. DT'].astype('str')

In [157]:
df_fechas_columnas.to_parquet('df_dts.parquet')

In [158]:
# df_cruce_fechas = df_mir6_filtro_yr.merge(df_fechas_columnas, left_on='Texto cab.documento',right_on='Nro. DT', how='left')

In [159]:
final = time.time()

In [160]:
time_difference = final - inicio

# Calculate minutes and seconds
minutes, seconds = divmod(time_difference, 60)

print(f"{minutes} minutos y {seconds} segundos")

2.0 minutos y 54.99405097961426 segundos

In [161]:
df_lc = pd.read_parquet('base_landcost.parquet')

In [162]:
df_lc.head()

,Tipo de cambio,Texto cab.documento,Referencia,Nombre del usuario,Nombre 1,Nº documento factura,Moneda,Impte.bruto factura,Fecha de entrada,Fecha de documento,Fe.descto.,Fe.contabilización,Emisor de factura,Ejercicio,Creado por,Código transacción,Clase de documento,Base retención,Asignación,Anulado con
0,"1,00000",19551,0236960581,SROJASF,NaN,5112952310,CLP,0.0,2024-01-11,2024-01-09,2024-01-09,2024-01-11,10000788,2024,NaN,MIRO,KI,0,0236960581,NaN
1,"1,00000",19555,0236960587,SROJASF,NaN,5112952457,CLP,0.0,2024-01-11,2024-01-09,2024-01-09,2024-01-11,10000788,2024,NaN,MIRO,KI,0,0236960587,NaN
2,"1,00000",19660,0236966448,SROJASF,NaN,5112956420,CLP,0.0,2024-01-16,2024-01-13,2024-01-13,2024-01-16,10000788,2024,NaN,MIRO,KI,0,0236966448,NaN
3,"1,00000",19760,0236965402,SROJASF,NaN,5112956464,CLP,25314.0,2024-01-16,2024-01-12,2024-01-12,2024-01-16,10000788,2024,NaN,MIRO,KI,0,0236965402,NaN
4,"1,00000",19663,0236969029,SROJASF,NaN,5112956505,CLP,63816.0,2024-01-16,2024-01-15,2024-01-15,2024-01-16,10000788,2024,NaN,MIRO,KI,0,0236969029,NaN

In [165]:
antiguo = pd.read_excel("C:/Users/lravlic/Inchcape/Planificación y Compras Chile - Documentos/Planificación y Compras KPI-Reportes/Reporteria/LAND COST/LAND COST 2024 JUNIO - OEM.xlsx", sheet_name = 'BD Final')

In [166]:
antiguo =

,Año contabilización,Mes contabilización,DT,Vía,Gasto proveedor,Freight,Sure,Derechos,Honorarios,Total general,Marca,Sector,Gastos Indirectos,Proveedor SAP,Proveedor,LAND COST,Origen,Equipo,VERSION SAP
0,2024,1,232558,Courier,4.299696e+05,314852.0,NaN,45266,15295.0,8.053826e+05,ALTERNATIVO UAC,OEM,805382.60,"HEFEI WINNING AUTO PARTS CO., LTD.",7565,1.873115,CHINA,Marcas Emergentes,S4
1,2024,1,232559,Courier,3.242687e+05,188736.0,NaN,24410,15295.0,5.527097e+05,ALTERNATIVO UAC,OEM,552709.74,"HEFEI WINNING AUTO PARTS CO., LTD.",7565,1.704480,CHINA,Marcas Emergentes,S4
2,2024,1,232581,Courier,6.136024e+05,405558.0,NaN,62371,15295.0,1.096826e+06,ALTERNATIVO UAC,OEM,1096826.45,"HEFEI WINNING AUTO PARTS CO., LTD.",7565,1.787520,CHINA,Marcas Emergentes,S4
3,2024,1,232609,Courier,5.643351e+05,1047303.0,NaN,89759,NaN,1.701397e+06,ALTERNATIVO UAC,OEM,1701397.10,"HEFEI WINNING AUTO PARTS CO., LTD.",7565,3.014870,CHINA,Marcas Emergentes,S4
4,2024,1,232620,Courier,6.091236e+05,136430.0,NaN,44361,15295.0,8.052096e+05,ALTERNATIVO UAC,OEM,805209.60,"HEFEI WINNING AUTO PARTS CO., LTD.",7565,1.321915,CHINA,Marcas Emergentes,S4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1092,2024,6,31629,Courier,5.979935e+05,25248.0,NaN,157726,NaN,7.809675e+05,RENAULT,OEM,182974.00,RENAULT,40000236,1.305980,FRANCIA,Marcas Tradicionales,R3
1093,2024,6,30842,Aereo,1.298320e+07,NaN,NaN,2530584,22148.0,1.553593e+07,JAC,OEM,2552732.00,ANHUI JIANGHUAI AUTOMOBILE GROUP,40001373,1.196618,CHINA,Marcas Emergentes,R3
1094,2024,6,31692,Courier,1.346675e+05,25248.0,NaN,35653,NaN,1.955685e+05,RENAULT,OEM,60901.00,RENAULT,40000236,1.452232,FRANCIA,Marcas Tradicionales,R3
1095,2024,6,31403,Aereo,3.875501e+06,NaN,NaN,1012451,15662.0,4.903614e+06,RENAULT,OEM,1028113.00,RENAULT,40000236,1.265285,FRANCIA,Marcas Tradicionales,R3
1096,2024,6,30973,Aereo,3.273220e+05,14568.0,NaN,NaN,NaN,3.418900e+05,RENAULT,OEM,14568.00,SOCIEDAD DE FABRICACION DE AUTOMOTO,40000186,1.044507,COLOMBIA,Marcas Tradicionales,R3